site_name: RA Dev Docs
site_url: https://retroachievements.org
repo_url: https://github.com/RetroAchievements/RADocs/
repo_name: RADocs Repo
nav:
  - Home: index.md
  - Design:
    - How RA Works: design/howraworks.md
    - Achievement Design: design/design.md
    - Achievement Scoring: design/scoring.md
    - Difficulty Scale and Balance: design/balance.md
    - Set Development Roadmap: design/roadmap.md
    - Achievement Creation Tips: design/tips.md
  - Basics:
    - Basics: basics/basics.md
    - Memory Inspector Overview: basics/meminsp.md
    - Achievement Editor: basics/editor.md
    - RAM Digging: basics/ramdigging.md
    - Code Notes: basics/codenotes.md
    - Game Identification: basics/id.md
  - Logic:
    - Overview: logic/overview.md
    - Reset If: logic/resetif.md
    - Reset Next If: logic/resetnextif.md
    - Pause If: logic/pauseif.md
    - And Next and Or Next: logic/andnextornext.md
    - Add Source: logic/addsource.md
    - Sub Source: logic/subsource.md
    - Add Hits and Sub Hits: logic/addhitssubhits.md
    - Add Address: logic/addaddress.md
    - Measured: logic/measured.md
    - Trigger: logic/trigger.md
    - Alt Groups: logic/altgroups.md
    - BitCount Size: logic/bitcount.md
    - Delta Values: logic/deltas.md
    - Hit Counts: logic/hitcounts.md
    - Prior Values: logic/prior.md
    - Combining Flags: logic/combiningflags.md
    - Logic Tips: logic/tips.md
    - Condition Syntax: logic/syntax.md
    - RATools: logic/ratools.md
  - Support:
    - Overview: support/overview.md
    - Cheat Protection: support/cheats.md
    - Demo Protection: support/demo.md
    - BIOS Protection: support/bios.md
    - Console Specific Tips: support/consoletips.md
    - Regional Compatibility: support/regional.md
  - Rich Presence:
    - Rich Presence Creation: richpresence/rp.md
  - Leaderboards:
    - Leaderboard Creation: leaderboards/lb.md
  - Badges:
    - Badge and Icon Creation: badges/badgeiconcreation.md
  - Resources:
    - Helpful Sites: resources/sites.md
    - Glossary of Developer Terms: resources/glossary.md
    - Minimum Versions: resources/minimumver.md
    - Systems Memory Mapping: resources/memmapping.md
    - Code Notes En Masse: resources/codenotesenmasse.md
    - Value Definition: resources/value.md
    - Address Watcher: resources/watcher.md
  - Examples:
    - Examples: examples/examples.md
    - Example 1: examples/ex1.md
    - Example 2: examples/ex2.md
    - Example 3: examples/ex3.md
    - Example 4: examples/ex4.md
    - Example 5: examples/ex5.md
    - Example 6: examples/ex6.md
    - Achievement Templates: examples/templates.md

theme:
  name: material
  favicon: img/favicon.ico
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde