site_name: RA Dev Docs
site_url: https://retroachievements.org
repo_url: https://github.com/RetroAchievements/RADocs/
repo_name: RADocs Repo
nav:
  - Home: index.md
  - Basics: basics.md
  - Logic:
    - Reset If: logic/resetif.md
    - Reset Next If: logic/resetnextif.md
    - Pause If: logic/pauseif.md
    - And Next and Or Next: logic/andnextornext.md
    - Add Source: logic/addsource.md
    - Sub Source: logic/subsource.md
    - Add Hits and Sub Hits: logic/addhitssubhits.md
    - Add Address: logic/addaddress.md
    - Measured: logic/measured.md
    - Trigger: logic/trigger.md
    - Alt Groups: logic/altgroups.md
    - BitCount Size: logic/bitcount.md
    - Delta Values: logic/deltas.md
    - Hit Counts: logic/hitcounts.md
    - Prior Values: logic/prior.md
  - Rich Presence:
    - Rich Presence Creation: richpresence/rp.md
  - Leaderboards:
    - Leaderboard Creation: leaderboards/lb.md
  - Badges:
    - Badge and Icon Creation: badges/badgeiconcreation.md
  - Other:
    - Achievement Design: other/design.md
    - Logic Features: other/logic.md
    - Achievement Scoring: other/scoring.md
    - Achievement Templates: other/templates.md
    - Combining Flags: other/combiningflags.md
    - Condition Syntax: other/syntax.md
    - Console Specific Tips: other/consoletips.md
    - Developer Docs: other/devdocs.md
    - Developer Projects: other/projects.md
    - Developer Resources: other/resources.md
    - Difficulty Scale and Balance: other/balance.md
    - Game Identification: other/id.md
    - Glossary of Developer Terms: other/glossary.md
    - Memory Inspector Overview: other/meminsp.md
    - Minimum Versions: other/minimumver.md
    - RALibretro: other/ralibretro.md
    - RATools: other/ratools.md
    - Real Examples: other/examples.md
    - Set Development Roadmap: other/roadmap.md
    - Value Definition: other/value.md
    - Tips and Tricks: other/tips.md
    - Testing for Demo Mode: other/demo.md
    - Systems Memory Mapping: other/memmapping.md
    - Regional Compatibility: other/regional.md
    - Code Notes En Masse: other/codenotesenmasse.md
  - Examples:
    - Example 1: examples/ex1.md
    - Example 2: examples/ex2.md
    - Example 3: examples/ex3.md
    - Example 4: examples/ex4.md
    - Example 5: examples/ex5.md
    - Example 6: examples/ex6.md

theme:
  name: material
  favicon: img/favicon.ico
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde