site_name: RA Dev Docs
site_url: https://retroachievements.github.io/
repo_url: https://github.com/RetroAchievements/RADocs/
repo_name: RADocs Repo
nav:
  - Home: index.md
  - Basics:
    - How RA Works: basics/how-ra-works.md
  - Logic:
    - Overview: logic/overview.md
  - Leaderboards:
    - Overview: leaderboards/overview.md
  - Rich Presence:
    - Overview: richpresence/overview.md
  - Support:
    - Overview: support//overview.md
  - Badge Creation:
    - Overview: badgecreation/overview.md
  - Resources:
    - Overview: resources/overview.md
  - RATools:
    - Overview: ratools/overview.md

theme:
  name: material
  favicon: img/favicon.ico
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde